---
# This role deploys a virtual machine
- name: merge overrides
  set_fact: settings={{ X86Platform | combine(Dependencies.X86Platform.overrides) }}

# Load OpenStack config (if not loaded)
- stat: path="{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
  register: st
- include_vars: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
  when: st.stat.exists and st.stat.isreg

- name: Launch X86 Instance
  local_action:
    module: os_server
    auth: "{{ item.value.auth }}"
    state: present
    name: "{{ settings.instance_name }}"
    image: "{{ settings.os_image }}"
    key_name: "{{ settings.os_keypair }}"
    timeout: 200
    flavor: "{{ settings.os_flavor }}"
    floating_ip_pools: "{{ settings.os_floating_ip_pools }}"
    nics:
      - network: "{{ settings.os_network }}"
    meta:
      hostname: "{{ settings.instance_name }}.openstacklocal"
  with_dict: "{{ clouds }}"
  register: nova

- debug:
    msg: "{{ nova.results[0].server }}"
  
- name: wait for ssh on instance
  command: >
    ssh -o BatchMode=yes -oStrictHostKeyChecking=no
    cloud-user@{{nova.results[0].server.public_v4}} true
  register: result
  until: result|success
  retries: 30
  delay: 10
  
- name: add instance to inventory
  add_host:
    name: "{{ settings.instance_name }}"
    groups: application
    ansible_host: "{{ nova.results[0].server.public_v4 }}"
    ansible_user: cloud-user
    become: yes

